# src/OC/PlatformBundle/Resources/config/routing.yml

accueil:
    path:     /
    defaults:
      _controller: rdnSiteBundle:Home:index

recettes:
    path:     /recettes
    defaults:
       _controller: rdnSiteBundle:Home:recettes

recette:
    path:     /recette/{id}
    defaults:
      _controller: rdnSiteBundle:Home:recette
    requirements:
      id: \d+

contact:
    path:     /contact
    defaults:
      _controller: rdnSiteBundle:Home:contact

create_account:
    path:     /create_account
    defaults:
      _controller: rdnSiteBundle:Home:create_account

add_message:
    path:     /add_message
    defaults:
      _controller: rdnSiteBundle:Home:add_message

add:
    path:     /add
    defaults:
      _controller: rdnSiteBundle:Home:add

recherche:
    path:     /recherche
    defaults:
      _controller: rdnSiteBundle:Home:recherche
